### ISSUE TITLE
Threaded-comments support not working

### ISSUE THREAD

**Issue by MohammedKhandwawala** [django-fluent/django-fluent-comments#109]
After including threaded-comments in the installed apps after going through the documentation it says form will adopt automatically it does but the replies are getting stored in the threaded-comments table and comments are getting stored in fluent comments table.

**Comment by vdboor** [comment]
Can you run `manage.py migrate_comments` ? This will populate the intermediate table that django-threadedcomments uses.

**Comment by panpanick** [comment]
I think the `manage.py migrate_comments` command is outdated. It is giving me this error:
```
Traceback (most recent call last):
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: no such function: TO_CHAR

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/threadedcomments/management/commands/migrate_comments.py", line 33, in handle
    cursor.execute(SQL)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/Users/jeanne/Env/phobeus_env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: no such function: TO_CHAR
```
