### ISSUE TITLE
Error on comment post with Django 1.10

### ISSUE THREAD

**Issue by Sheepzez** [django-fluent/django-fluent-comments#90]
When posting a comment, I'm receiving an error on this line: https://github.com/django-fluent/django-fluent-comments/blob/master/fluent_comments/moderation.py#L130

The stracktrace is as follows:

Internal Server Error: /blog/comments/post/ajax/
Traceback (most recent call last):
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/fluent_comments/views.py", line 88, in post_comment_ajax
    request = request
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/django_comments/moderation.py", line 351, in pre_save_moderation
    if not moderation_class.allow(comment, content_object, request):
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/fluent_comments/moderation.py", line 63, in allow
    if self._akismet_check(comment, content_object, request):
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/fluent_comments/moderation.py", line 108, in _akismet_check
    akismet_data = self._get_akismet_data(blog_url, comment, content_object, request)
  File "/home/isaac/envs/personal-site/lib/python3.5/site-packages/fluent_comments/moderation.py", line 130, in _get_akismet_data
    if comment.user_id and comment.user.is_superuser():
TypeError: 'bool' object is not callable

Quite clear that comment.user.is_superuser is a field and not a method. Was this changed in Django 1.10?

**Comment by vdboor** [comment]
This seems like an accidental thing, as `is_superuser` was never a method. Merged it!
